name: CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to release"
        required: true
        default: "1.0.0"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Print the version
        run: echo "Releasing version ${{ inputs.version }}"